version: "3.8"

services:
  db:
    image: "postgres:11-alpine"

    env_file:
      - ./.env

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: .

    command: sh -c "pytest --cov --cov-report xml:./coverage.xml"

    env_file:
      - ./.env

    volumes:
      - .:/code

    depends_on:
      db:
        condition: service_healthy

  check_style:
    build: .

    command: flake8
