version: "3.8"

services:
  db:
    image: "postgres:11-alpine"

    env_file:
      - ./.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .

    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8001"

    env_file:
      - ./.env

    volumes:
      - .:/code

    ports:
      - "8001:8001"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
