name: Estilo

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  check_style:
    name: Verificar Estilo de Código
    runs-on: ubuntu-latest

    steps:
      - name: Conferir repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Evita clones rasos

      - name: Criar arquivo .env
        run: |
          touch .env
          echo SECRET_KEY=secret_key >> .env
          echo DEBUG=True >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          cat .env

      - name: Executar flake8  
        run: sudo docker-compose run web flake8
