name: Testes

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Verificar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Conferir repositório
        uses: actions/checkout@v2

      - name: Criar arquivo .env
        run: |
          touch .env
          echo SECRET_KEY=secret_key >> .env
          echo DEBUG=True >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env

      - name: Executar pytest  
        run: sudo docker-compose -f .github/docker-compose.actions.yml --project-directory . run test
